AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Buckets
Resources:
  SageMakerS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'sagemaker-${AWS::Region}-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "POST"
            AllowedOrigins:
              - "*"
            ExposedHeaders: []
Outputs:
  BucketName:
    Value: !Ref SageMakerS3Bucket
    Description: Name of the Amazon S3 bucket with CORS enabled.
