apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim-vol-validation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi
