name: disaster_response_hackathon 
dependencies:
  - python=3.9
  - ipykernel
  - pip
  - pip:
    - matplotlib
    - plotly_express
    - folium
    - seaborn
    - geotiff
    - geojson
    - numpy
    - numba
    - cuda-python
    - pandas
    - geopandas
    - OSMPythonTools
    - pystac
    - rasterio
    - shapely
    - timm
    - pyproj
    - earthpy
    - sentinelhub
    - torch
    - torchvision
    - scikit-learn

