channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.0.4
- pip:
  - brotlipy==0.7.0
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - fsspec==2022.3.0
  - lz4==4.0.0
  - pillow==9.1.0
  - pyarrow==6.0.1
  - pysocks==1.7.1
  - sagemaker==2.86.2
  - scipy==1.8.0
  - tensorflow==2.8.0
name: mlflow-env
